version : 1
disable_existing_loggers: False
formatters:
    simpleFormater:
        format: '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        formatter: simpleFormater
        level: DEBUG
root:
    level: DEBUG
    handlers: [console]
